version: '3.3'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: maxmcd/webtty-node-go:no-libssl
  web-client:
    build: 
      context: .
      dockerfile: ./web-client/Dockerfile
    image: maxmcd/webtty-client
    ports:
      - 8080:80
